//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.20 at 09:21:44 AM MSK 
//


package ru.yajaneya.SpringFM1GeekbrainsDz7.soap.categories;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="category" type="{http://www.yajaneya.ru/SpringFM1GeekbrainsDz7/categories}categorySoap"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "category"
})
@XmlRootElement(name = "getCategoryByCategoryNameResponse")
public class GetCategoryByCategoryNameResponse {

    @XmlElement(required = true)
    protected CategorySoap category;

    /**
     * Gets the value of the category property.
     *
     * @return
     *     possible object is
     *     {@link CategorySoap }
     *
     */
    public CategorySoap getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     *
     * @param value
     *     allowed object is
     *     {@link CategorySoap }
     *     
     */
    public void setCategory(CategorySoap value) {
        this.category = value;
    }

}
