//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.20 at 09:21:44 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.yajaneya.ru/SpringFM1GeekbrainsDz7/products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.yajaneya.SpringFM1GeekbrainsDz7.soap.products;
